// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnaWB8sk3xjqa3GXm_sfMw5SIeSjE7y0k',
    appId: '1:24924827376:web:e26b46bd9e609002aa5c35',
    messagingSenderId: '24924827376',
    projectId: 'iti-project-8a8e6',
    authDomain: 'iti-project-8a8e6.firebaseapp.com',
    storageBucket: 'iti-project-8a8e6.firebasestorage.app',
    measurementId: 'G-G676BW4FDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSAdKJ5PY_cAeMsK22YbxGZ_YmXGPagc',
    appId: '1:24924827376:android:f712045d8b12531baa5c35',
    messagingSenderId: '24924827376',
    projectId: 'iti-project-8a8e6',
    storageBucket: 'iti-project-8a8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RBlA3QDY2yYxcD22eLE91DiNzmrtQrA',
    appId: '1:24924827376:ios:5090244015ad2469aa5c35',
    messagingSenderId: '24924827376',
    projectId: 'iti-project-8a8e6',
    storageBucket: 'iti-project-8a8e6.firebasestorage.app',
    iosBundleId: 'com.example.firstFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RBlA3QDY2yYxcD22eLE91DiNzmrtQrA',
    appId: '1:24924827376:ios:5090244015ad2469aa5c35',
    messagingSenderId: '24924827376',
    projectId: 'iti-project-8a8e6',
    storageBucket: 'iti-project-8a8e6.firebasestorage.app',
    iosBundleId: 'com.example.firstFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnaWB8sk3xjqa3GXm_sfMw5SIeSjE7y0k',
    appId: '1:24924827376:web:9f3e041425c69e43aa5c35',
    messagingSenderId: '24924827376',
    projectId: 'iti-project-8a8e6',
    authDomain: 'iti-project-8a8e6.firebaseapp.com',
    storageBucket: 'iti-project-8a8e6.firebasestorage.app',
    measurementId: 'G-PDFN1YPWT9',
  );
}
